# This workflow will build and push a node.js application to an Azure Web App when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure App Service web app.
# For instructions see https://docs.microsoft.com/en-us/azure/app-service/quickstart-nodejs?tabs=linux&pivots=development-environment-cli
#
# To configure this workflow:
#
# 1. Download the Publish Profile for your Azure Web App. You can download this file from the Overview page of your Web App in the Azure Portal.
#    For more information: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
#
# 2. Create a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE, paste the publish profile contents as the value of the secret.
#    For instructions on obtaining the publish profile see: https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret
#
# 3. Change the value for the AZURE_WEBAPP_NAME. Optionally, change the AZURE_WEBAPP_PACKAGE_PATH and NODE_VERSION environment variables below.
#
# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more information on the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

on:
  push:
    branches: [ "<main>
  <div class="mb-6">
    <label for="prompt" class="block mb-2 text-lg font-semibold text-gray-700">الوصف (Prompt):</label>
    <textarea
      id="prompt"
      rows="3"
      class="w-full p-3 border border-gray-300 rounded-lg shadow-sm focus:ring-2 focus:ring-blue-500 focus:border-transparent transition duration-150 ease-in-out"
      placeholder="مثال: رائد فضاء يركب حصانًا على سطح المريخ"
    ></textarea>
  </div>

  <button id="generateButton" class="w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-3 px-6 rounded-lg shadow-md hover:shadow-lg transition duration-300 ease-in-out transform hover:scale-105 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50">
    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 inline-block ml-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
    </svg>
    توليد الصورة
  </button>

  <div id="loadingIndicator" class="loader mt-8 hidden"></div>
  <div id="errorMessage" class="mt-6 p-4 bg-red-100 text-4 border-red-500 rounded-r-lg hidden"></div>
  <div id="infoMessage" class="mt-6 p-4 bg-blue-100 text-blue-800 border-l-4 border-blue-500 rounded-r-lg hidden"></div>

  <!-- حاوية عرض الصورة وزر التنزيل -->
  <div id="imageContainer" class="mt-8 p-2 border border-dashed border-gray-300 rounded-lg bg-gray-50 min-h-[250px] flex flex-col items-center justify-center hidden">
    <div id="imageWrapper" class="gallery-img-wrapper w-full flex justify-center">
      <img id="generatedImage" src="#" alt="الصورة المولدة" class="max-w-full max-h-[500px] rounded-lg shadow-lg hidden" />
    </div>
    <p id="placeholderText" class="text-gray-400 text-lg">سيتم عرض الصورة هنا بعد إنشائها.</p>
    <button id="downloadButton" class="w-full bg-green-600 hover:bg-green-700 text-white font-semibold py-3 px-6 mt-4 rounded-lg shadow-md hover:shadow-lg transition duration-300 ease-in-out transform hover:scale-105 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50 hidden">
      تنزيل الصورة
    </button>
  </div>

  <!-- لوحة تخصيص الصورة -->
  <div id="editControls" class="mt-8 p-4 bg-white rounded-xl shadow-md w-full hidden">
    <h2 class="text-xl font-bold text-gray-800 mb-4">تخصيص الصورة</h2>
    <div class="grid grid-cols-1 gap-4">
      <div>
        <label for="brightness" class="block text-gray-700">السطوع (<span id="brightnessVal">100</span>%)</label>
        <input id="brightness" type="range" min="50" max="200" value="100" class="w-full">
      </div>
      <div>
        <label for="contrast" class="block text-gray-700">التباين (<span id="contrastVal">100</span>%)</label>
        <input id="contrast" type="range" min="50" max="150" value="100" class="w-full">
      </div>
      <div>
        <label for="saturation" class="block text-gray-700">التشبع (<span id="saturationVal">100</span>%)</label>
        <input id="saturation" type="range" min="0" max="200" value="100" class="w-full">
      </div>
      <div>
        <label for="blur" class="block text-gray-700">التشويش (<span id="blurVal">0</span>px)</label>
        <input id="blur" type="range" min="0" max="10" value="0" class="w-full">
      </div>
      <div>
        <label for="rotation" class="block text-gray-700">التدوير (<span id="rotationVal">0</span>°)</label>
        <input id="rotation" type="range" min="0" max="360" value="0" class="w-full">
      </div>
    </div>
    <div class="mt-4 flex space-x-4">
      <button id="applyFiltersButton" class="w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-2 px-4 rounded">تطبيق التعديلات</button>
      <button id="resetFiltersButton" class="w-full bg-gray-600 hover:bg-gray-700 text-white font-semibold py-2 px-4 rounded">إعادة ضبط</button>
    </div>
  </div>

  <!-- لوحة اقتصاص الصورة -->
  <div id="cropControls" class="mt-8 p-4 bg-white rounded-xl shadow-md w-full hidden">
    <h2 class="text-xl font-bold text-gray-800 mb-4">تعديل الصورة (اقتصاص)</h2>
    <div class="grid grid-cols-2 gap-4">
      <div>
        <label for="cropX" class="block text-gray-700">الإحداثي X</label>
        <input id="cropX" type="number" value="0" class="w-full p-2 border border-gray-300 rounded">
      </div>
      <div>
        <label for="cropY" class="block text-gray-700">الإحداثي Y</label>
        <input id="cropY" type="number" value="0" class="w-full p-2 border border-gray-300 rounded">
      </div>
      <div>
        <label for="cropWidth" class="block text-gray-700">العرض</label>
        <input id="cropWidth" type="number" value="600" class="w-full p-2 border border-gray-300 rounded">
      </div>
      <div>
        <label for="cropHeight" class="block text-gray-700">الارتفاع</label>
        <input id="cropHeight" type="number" value="400" class="w-full p-2 border border-gray-300 rounded">
      </div>
    </div>
    <div class="mt-4">
      <button id="cropButton" class="w-full bg-purple-600 hover:bg-purple-700 text-white font-semibold py-2 px-4 rounded">اقتصاص الصورة</button>
    </div>
  </div>
  
</main>

<footer class="mt-10 text-center text-sm text-gray-500">
  <p>مدعوم بالذكاء الاصطناعي | تصميم لـ Gemini</p>
</footer>" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '20.x'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: node-app
        path: .

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
